server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost/hr?serverTimezone=UTC
    username: roma
    password: 123
=======
    url: jdbc:mysql://localhost/hr
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
>>>>>>> d19c729b63af708587ba856fc95ab09c85a471d9
